# Generated by Django 4.1.4 on 2023-01-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Author_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_Password', models.CharField(max_length=50)),
                ('Stud_Name', models.CharField(max_length=50)),
                ('Stud_Phno', models.BigIntegerField()),
                ('Stud_Sem', models.IntegerField()),
                ('Stud_Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrarymanagementApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('Book_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrarymanagementApp.books')),
                ('Student_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrarymanagementApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='Course_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrarymanagementApp.course'),
        ),
    ]
